/*
URLShortener API

Testing DefaultAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Leopold1975/url_shortener/internal/shortener/server/restserver/openapi"
)

func Test_openapi_DefaultAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultAPIService ShortUrlDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var shortUrl string

		httpRes, err := apiClient.DefaultAPI.ShortUrlDelete(context.Background(), shortUrl).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ShortUrlGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var shortUrl string

		resp, httpRes, err := apiClient.DefaultAPI.ShortUrlGet(context.Background(), shortUrl).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService UrlPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DefaultAPI.UrlPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
