openapi: 3.0.0
info:
  title: URLShortener API
  version: "1.0"
servers:
- url: http://localhost:7770/v1
paths:
  /docs:
    get:
      responses:
        "200":
          content:
            text/html:
              schema:
                type: string
          description: Successfully show api docs page
      summary: Shows docs
  /url:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_url_post_request'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_url_post_201_response'
          description: Successfully created short URL
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_url_post_400_response'
          description: Can not create short URL
      summary: Create a short URL
  /url/{short_url}:
    delete:
      parameters:
      - explode: false
        in: path
        name: short_url
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: Short URL successfully deleted
        "404":
          description: Short URL not found
      summary: Delete the short URL
    get:
      parameters:
      - explode: false
        in: path
        name: short_url
        required: true
        schema:
          type: string
        style: simple
      - explode: true
        in: query
        name: info
        required: false
        schema:
          type: boolean
        style: form
      responses:
        "303":
          description: Redirect to long URL
          headers:
            Location:
              description: URL to redirect to
              explode: false
              schema:
                format: uri
                type: string
              style: simple
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/URL'
          description: JSON containing the long URL
        "404":
          description: Short URL not found
      summary: Redirect to long URL or get long URL info
components:
  schemas:
    URL:
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        shortUrl: shortUrl
        clicks: 0
        longUrl: longUrl
      properties:
        longUrl:
          type: string
        shortUrl:
          type: string
        createdAt:
          format: date-time
          type: string
        clicks:
          format: int64
          type: integer
      type: object
    _url_post_request:
      properties:
        long_url:
          type: string
      required:
      - long_url
      type: object
    _url_post_201_response:
      example:
        short_url: short_url
      properties:
        short_url:
          type: string
      type: object
    _url_post_400_response:
      example:
        error: error
      properties:
        error:
          type: string
      type: object
